---
# Master Playbook: abstract_skeleton.yml
- 
  hosts: s1
  become: true
  



  # tasks:
  #   - name: "install git and which packages"
  #     block:
  #       - name: "Installing Git"
  #         package:
  #           name: git
  #           state: present
  #       - name: "Installaing Which"
  #         package:
  #           name: which
  #           state: present
  #     rescue:
  #       - name: "Remove packages"
  #         yum: 
  #           name: git-core-2.43.5-2.el8_10.x86_64
  #           state: absent
  #       - package: 
  #           name: which 
  #           state: absent
  #     always:
  #       - debug:
  #           msg: "Block Executed!!!"


      
    
  # tasks:
  #   - name: "Sleep"
  #     command: /bin/sleep 10
  #     async: 20
  #     poll: 0
  #     register: output
    
  #   - name: "Check User Exixst"
  #     command: id vibi
  #     ignore_errors: yes
  #     register: "user_check"
    
  #   - name: "add User"
  #     shell: useradd vibi
  #     when: user_check.rc != 0


  #   - name: "Check the status"
  #     async_status:
  #       jid: "{{ output.ansible_job_id }}"
  #     register: job_result
  #     until: job_result.finished
  #     retries: 5


  # tasks:
  #   - name: "Shell Module"
  #     shell: echo "vibishnathannnnn" > /txt1.txt
  #     register: output
  # post_tasks:
  #   - debug:
  #       msg: "{{ output }}"


  # tasks:
  #   - name: "CMD"
  #     command: userdel vinith
  #     register: result
  # post_tasks:
  #   - debug:
  #       msg: "return code is: {{ result.rc }} and the entire result found this {{ result }}"



  # tasks:
  #   - name: "Checking Vars"
  #     debug:
  #       msg: "{{ a1 }}"

  # vars:
  #   motd: "Welcome Vbishnathan MOTD is updated"
  # tasks:
  #   - name: "Task 1 MOTD"
  #     copy:
  #       dest: /etc/motd
  #       content: "{{ motd }}"
  #     when: ansible_distribution == "RedHat"
  #     notify: "motd_changed"
  
  # handlers:
  #   - name: "motd_changed"
  #     debug:
  #       msg: "MOTD changed "


  # vars:
  # tasks:
  #   - name: "Installaing Nginx"
  #     package:
  #       name: nginx
  #       state: present
  #     notify:
  #       "Nginx Installed"

  #   - name: "Restart Nginx"
  #     service:
  #       name: nginx
  #       state: restarted
      
  # handlers:
  #   - name: "Nginx Installed"
  #     uri:
  #       url: http://{{ ansible_default_ipv4.address }}
  #       status_code:
  #         - 200
#
...



